### ISSUE TITLE
Please update rubygems. (Rubygemsのバージョンを更新してください)

### ISSUE THREAD

**Issue by sakuma** [jue58/kintone#7]
Last updated version is 0.1.4 on April 7, 2016.
I want to use a new function (master branch).
Please update [Rubygems](https://rubygems.org/gems/kintone)

------------------------------

最近 KintoneのAPIを使うプロダクトを開発しており、その際にこのgemを使わせて頂いています。
ただ、Rubygemsのバージョンは最新ではないようです。masterブランチの機能を使いたいので更新をおねがいします 🙇

**Comment by jue58** [comment]
@sakuma Sorry for replying late. I've released v0.1.5. Please let me know if any problem.
いろいろ遅くてすみません...v0.1.5をリリースしました。何か問題があったら知らせてください。
